# Generated by Django 4.0 on 2021-12-15 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='branch',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
